# Documentation: https://github.com/compose-spec/compose-spec/blob/master/spec.md
# Purpose: Build local containers for the Mutillidae environment

version: '3.7'
services:

  database:
    container_name: database
    image: webpwnized/mutillidae:database
    build: 
        context: ./database
        dockerfile: Dockerfile
    networks:
      - datanet   

  database_admin:
    container_name: database_admin
    depends_on:
      - database
    image: webpwnized/mutillidae:database_admin
    build:
        context: ./database_admin
        dockerfile: Dockerfile
    ports:
      - 127.0.0.1::80
    networks:
      - datanet   
  www-sqli:
    container_name: www-sqli
    depends_on:
      - database
    image: webpwnized/mutillidae:www-sqli
    build:
      context: ./www-sqli
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1::80
      - 127.0.0.1::443
    networks:
      - datanet
    environment:
      - FLAG=marc
  www-ci:
    container_name: www-ci
    depends_on:
      - database
    image: webpwnized/mutillidae:www-ci
    build:
      context: ./www-ci
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1::80
      - 127.0.0.1::443
    networks:
      - datanet
    environment:
      - FLAG=marc
  www-jwt:
    container_name: www-jwt
    depends_on:
      - database
    image: webpwnized/mutillidae:www-jwt
    build:
      context: ./www-jwt
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1::80
      - 127.0.0.1::443
    networks:
      - datanet
    environment:
      - FLAG=marc

# Create network segments for the containers to use
networks:
    datanet:
